---

- include: install.yml
  tags:
    - database:nosql
    - mongodb
    - install
    - mongodb-install

- include: config.yml
  tags:
    - database:nosql
    - mongodb
    - config
    - mongodb-config

- include: service.yml
  tags:
    - database:nosql
    - mongodb
    - service
    - mongodb-service
